// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/standard.proto

// package name will be call by other package,
// this same proto/path/to/package/file.proto -> path.to.package

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for JWT-based operations (shared by multiple functions)
type ClientJwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientJwt) Reset() {
	*x = ClientJwt{}
	mi := &file_common_standard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientJwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJwt) ProtoMessage() {}

func (x *ClientJwt) ProtoReflect() protoreflect.Message {
	mi := &file_common_standard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJwt.ProtoReflect.Descriptor instead.
func (*ClientJwt) Descriptor() ([]byte, []int) {
	return file_common_standard_proto_rawDescGZIP(), []int{0}
}

func (x *ClientJwt) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *ClientJwt) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

// Standard response structure for all APIs
type StandardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Response code (e.g., 0 for success)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Response message
	Payload       *anypb.Any             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Payload containing specific response data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_common_standard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_standard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_common_standard_proto_rawDescGZIP(), []int{1}
}

func (x *StandardResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StandardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StandardResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_common_standard_proto protoreflect.FileDescriptor

const file_common_standard_proto_rawDesc = "" +
	"\n" +
	"\x15common/standard.proto\x12\x06common\x1a\x19google/protobuf/any.proto\"4\n" +
	"\tClientJwt\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\"p\n" +
	"\x10StandardResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayloadB9Z7github/weeback/grpc-project-template/pb/common;commonpbb\x06proto3"

var (
	file_common_standard_proto_rawDescOnce sync.Once
	file_common_standard_proto_rawDescData []byte
)

func file_common_standard_proto_rawDescGZIP() []byte {
	file_common_standard_proto_rawDescOnce.Do(func() {
		file_common_standard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_standard_proto_rawDesc), len(file_common_standard_proto_rawDesc)))
	})
	return file_common_standard_proto_rawDescData
}

var file_common_standard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_standard_proto_goTypes = []any{
	(*ClientJwt)(nil),        // 0: common.ClientJwt
	(*StandardResponse)(nil), // 1: common.StandardResponse
	(*anypb.Any)(nil),        // 2: google.protobuf.Any
}
var file_common_standard_proto_depIdxs = []int32{
	2, // 0: common.StandardResponse.payload:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_standard_proto_init() }
func file_common_standard_proto_init() {
	if File_common_standard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_standard_proto_rawDesc), len(file_common_standard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_standard_proto_goTypes,
		DependencyIndexes: file_common_standard_proto_depIdxs,
		MessageInfos:      file_common_standard_proto_msgTypes,
	}.Build()
	File_common_standard_proto = out.File
	file_common_standard_proto_goTypes = nil
	file_common_standard_proto_depIdxs = nil
}
